### PR TITLE
Intermediate keys

### PR DESCRIPTION
**Pull request by fbaiodias**
Hey!

Changed the way we set errors when a key is passed, so that it is possible to validate intermediate keys and their children.
This also fixes some bugs on arrays of objects validation, so I added a couple of tests for that.

Let me know what you think :)

### CODE REVIEW

**Comment by jurassix** [comment]
Thanks! I'll review and merge in today.

**Comment by jurassix** [comment]
Thanks again!

**Comment by fbaiodias** [comment]
@jurassix, can you please publish this to npm? Thanks!

**Comment by jurassix** [comment]
@xicombd released as v0.3.1 
Thanks again!

**Pull request merged**
